# Site settings

title: "3P Puchar"
email: jakoor@o2.pl
description: "CO."
highlighter: null

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
 

# Postal address (add as many lines as necessary)
address:
  - line: Domaradz ,90210

# Build settings
markdown: kramdown
permalink: pretty
